"""
main.py
--------
The Orchestrator -- the brain of the multi-agent system.
Wires together: Router -> (RAG | SQL | General) -> Response formatter

This is also the entry point for tests and the CLI demo.
The Streamlit UI (ui/app.py) imports and uses the Orchestrator class.

Architecture recap (for interviews):
  User query
      |
      ▼
  RouterAgent   --classifies intent--►  "rag" | "sql" | "general"
      |
      ├- "rag"     --► RAGAgent     --► retrieves docs -> LLM answer
      ├- "sql"     --► SQLAgent     --► generates SQL -> executes -> formats
      └- "general" --► GeneralAgent --► plain LLM answer
                                              |
                                              ▼
                                        ResponseAgent  (formats + cites)
                                              |
                                              ▼
                                        Final answer string
"""

import sys, io
if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", errors="replace")

from agents.router_agent     import RouterAgent
from agents.rag_agent        import RAGAgent
from agents.sql_agent        import SQLAgent
from agents.general_agent    import GeneralAgent
from agents.gemini_doc_agent import GeminiDocAgent
from agents.response_agent   import ResponseAgent
from agents.base_agent       import AgentResponse
from utils.memory          import ConversationMemory
from utils.logger          import get_logger

log = get_logger("Orchestrator")


class Orchestrator:
    """
    Central coordinator for the multi-agent pipeline.
    Instantiate once, then call .process(query) for each user message.
    """

    def __init__(self):
        log.info("Initialising multi-agent system...")
        self.router    = RouterAgent()
        self.rag       = RAGAgent()
        self.sql       = SQLAgent()
        self.general   = GeneralAgent()
        self.doc       = GeminiDocAgent()   # Native Gemini PDF/DOCX analyser
        self.formatter = ResponseAgent()
        self.memory    = ConversationMemory()

        # -- Auto-ingest sample docs if store is empty ----------------------
        from rag.vector_store import vector_store
        from rag.document_processor import load_all_from_directory
        if vector_store.doc_count() == 0:
            log.info("Vector store is empty. Checking sample_docs for initial ingestion...")
            chunks = load_all_from_directory(config.DOCS_UPLOAD_PATH)
            if chunks:
                vector_store.add_documents(chunks)

        log.info("All agents ready [OK]")

    def process(self, query: str) -> tuple[str, str]:
        """
        Full pipeline for one user message.

        Returns:
            (formatted_answer, agent_name_used)
        """
        log.info(f"New query: '{query}'")

        # -- 1. Store user turn in memory -----------------------------------
        self.memory.add_user(query)
        recent_context = self.memory.get_recent_context(n=4)

        # -- 2. Route -------------------------------------------------------
        route_response = self.router._safe_run(query)
        route          = route_response.metadata.get("route", "general")

        # -- 3. Dispatch to the appropriate agent ---------------------------
        from agents.gemini_doc_agent import has_documents

        # If docs are uploaded, route doc-related queries to GeminiDocAgent
        if route == "rag" and has_documents():
            log.info("Documents present — routing to GeminiDocAgent for native analysis")
            route = "doc"

        agent_map = {
            "rag":     self.rag,
            "sql":     self.sql,
            "general": self.general,
            "doc":     self.doc,
        }
        agent    = agent_map.get(route, self.general)
        response: AgentResponse = agent._safe_run(query, context=recent_context)

        # -- 3b. FALLBACK: If RAG/Doc couldn't find the answer, try General --
        if route in ("rag", "doc") and "not found" in response.answer.lower():
            log.info("Doc/RAG search yielded no results -- falling back to General")
            response = self.general._safe_run(query, context=recent_context)

        # -- 4. Format the final response -----------------------------------
        formatted = self.formatter.format(response)

        # -- 5. Store assistant turn in memory ------------------------------
        self.memory.add_assistant(formatted, agent_used=response.agent_name)

        log.info(f"Response generated by {response.agent_name} | "
                 f"success={response.success}")

        return formatted, response.agent_name

    def get_welcome(self) -> str:
        return self.formatter.format_welcome()

    def clear_memory(self) -> None:
        self.memory.clear()
        log.info("Conversation memory cleared")


# -- CLI demo (run: python main.py) --------------------------------------------

if __name__ == "__main__":
    from database.db_setup import seed_database
    from rag.document_processor import load_all_from_directory
    from rag.vector_store import vector_store

    print("\n" + "="*60)
    print("  Multi-Agent Knowledge Assistant  --  CLI Demo")
    print("="*60 + "\n")

    # Seed the database
    seed_database()

    # Load sample documents if any
    chunks = load_all_from_directory("./sample_docs")
    if chunks:
        vector_store.add_documents(chunks)
        print(f"[OK] Loaded {len(chunks)} document chunks into vector store\n")

    orchestrator = Orchestrator()

    # -- Run 3 demo queries -------------------------------------------------
    demo_queries = [
        "Show me all students with marks above 80",
        "What is the average score in Computer Science?",
        "What is Retrieval Augmented Generation?",
    ]

    for q in demo_queries:
        print(f"\n{'-'*50}")
        print(f"USER: {q}")
        print(f"{'-'*50}")
        answer, agent = orchestrator.process(q)
        print(answer)
        print(f"\n[Handled by: {agent}]")

    print("\n" + "="*60)
    print("  Demo complete. Run `streamlit run ui/app.py` for the UI.")
    print("="*60 + "\n")
